apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kube-agent-chart.fullname" . }}
  labels:
    {{- include "kube-agent-chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "kube-agent-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kube-agent-chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kube-agent-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - api-server
            - start
          env:
            - name: TARGET
              value: {{ .Values.mw.target }}
            - name: MW_API_KEY
              value: {{ .Values.mw.apiKey }}
          # ports:
          #   - name: http
          #     containerPort: 4318
          #     protocol: TCP
          #   - name: grpc
          #     containerPort: 4317
          #     protocol: TCP
          #   - name: fluent
          #     containerPort: 8006
          #     protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 4317
          readinessProbe:
            tcpSocket:
              port: 4317
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
