apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vision-scheduler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vision-scheduler
subjects:
  - kind: ServiceAccount
    name: vision-scheduler
    namespace: {{ .Release.Namespace }}