apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vision-scheduler-leader-election
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: odigos-leader-election-role
subjects:
- kind: ServiceAccount
  name: vision-scheduler
