kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    k8s-app: {{ .Values.app.name }}
  name: {{ .Values.role.name }}-update
  namespace: {{ .Values.namespace.name }}
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "update"]
- apiGroups: ["apps"]
  resources: ["daemonsets", "deployments"]
  verbs: ["get", "update"]