apiVersion: v1
kind: Secret
metadata:
  name: middleware-secret
  namespace: {{ .Values.namespace.name }}
  labels:
      {{- include "mw-kube-agent.labels" . | nindent 4 }}
type: Opaque

data:
  api-key: {{- if .Values.mw.apiKeyFromExistingSecret.enabled }}
             {{- $secretName := $.Values.mw.apiKeyFromExistingSecret.name }}
             {{- $secretKey := $.Values.mw.apiKeyFromExistingSecret.key }}
             {{- $namespace := $.Values.namespace.name }}
             {{- $secret := lookup "v1" "Secret" $namespace $secretName }}
             {{- if $secret}}
               {{- $apiKey := index $secret.data $secretKey }}
               {{- if $apiKey }}
                 {{ $apiKey }}
               {{- else }}
                 {{- fail "Could not read MW API Key from existing secret" }}
               {{- end }}
             {{- end }}
             
           {{- else }}
             {{ .Values.mw.apiKey | toString | b64enc }}   
           {{- end }}
