{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    k8s-app: {{ .Values.app.name }}
  name: {{ .Values.serviceAccount.name }}-update
  namespace: {{ .Values.namespace.name }}
{{- end }}