apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vision-autoscaler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vision-autoscaler
subjects:
- kind: ServiceAccount
  name: vision-autoscaler
  namespace: {{ .Release.Namespace }}
