apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vision-autoscaler
rules:
  - apiGroups:
      - vision.middleware.io
    resources:
      - instrumentedapplications
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - vision.middleware.io
    resources:
      - instrumentedapplications/finalizers
    verbs:
      - update
  - apiGroups:
      - vision.middleware.io
    resources:
      - instrumentedapplications/status
    verbs:
      - get
      - patch
      - update