apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: visioncart
  namespace: {{ .Release.Namespace }}
  labels:
    app: visioncart
spec:
  selector:
    matchLabels:
      app: visioncart
  template:
    metadata:
      labels:
        app: visioncart
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
        - key: node.kubernetes.io/os
          operator: Equal
          value: windows
          effect: NoSchedule
      serviceAccountName: visioncart
      hostNetwork: true
      hostPID: true
      dnsPolicy: ClusterFirstWithHostNet
{{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 6 }}
{{- end }}
      containers:
        - name: visioncart
          image: "{{ .Values.visioncart.image.repository }}:{{ .Values.visioncart.image.tag }}"
          imagePullPolicy: IfNotPresent
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          securityContext:
            privileged: true
          volumeMounts:
            - name: run-dir
              mountPath: /run
              mountPropagation: Bidirectional
            - name: var-dir
              mountPath: /var
              mountPropagation: Bidirectional
            - name: odigos
              mountPath: /odigos
              mountPropagation: Bidirectional
      volumes:
        - name: run-dir
          hostPath:
            path: /run
        - name: var-dir
          hostPath:
            path: /var
        - name: odigos
          hostPath:
            path: /odigos
