---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.certSecretName }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "mw-kube-agent.labels" . | nindent 4 }}
type: {{ .Values.secret.type }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.csrfSecretName }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "mw-kube-agent.labels" . | nindent 4 }}
type: {{ .Values.secret.type }}
data:
  csrf: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.keyHolderSecretName }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "mw-kube-agent.labels" . | nindent 4 }}
type: {{ .Values.secret.type }}