apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vision-ui
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
    - ""
  resources:
    - secrets
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - odigos.io
  resources:
    - collectorsgroups
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - odigos.io
  resources:
    - collectorsgroups/finalizers
  verbs:
    - update
- apiGroups:
    - odigos.io
  resources:
    - collectorsgroups/status
  verbs:
    - get
    - patch
    - update
- apiGroups:
    - odigos.io
  resources:
    - destinations
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - odigos.io
  resources:
    - destinations/finalizers
  verbs:
    - update
- apiGroups:
    - odigos.io
  resources:
    - destinations/status
  verbs:
    - get
    - patch
    - update
- apiGroups:
    - odigos.io
  resources:
    - odigosconfigurations
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - odigos.io
  resources:
    - odigosconfigurations/finalizers
  verbs:
    - update