apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vision-ui
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vision-ui
subjects:
- kind: ServiceAccount
  name: vision-ui
