apiVersion: v1
kind: Service
metadata:
  name: odigos-ui
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: odigos-ui